FROM sonarqube:lts-alpine
RUN wget -O /opt/sonarqube/extensions/plugins/sonar-typescript-plugin-1.7.0.2893.jar https://github.com/SonarSource/SonarTS/releases/download/v1.7.0/sonar-typescript-plugin-1.7.0.2893.jar
RUN wget -O /opt/sonarqube/extensions/plugins/sonar-javascript-plugin-4.2.1.6529.jar https://github.com/SonarSource/SonarJS/releases/download/4.2.1.6529/sonar-javascript-plugin-4.2.1.6529.jar
